import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: [
    './favicon.ico'
  ]
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`{inter.className} w-screen h-dvh`}>
        {children}
      </body>
    </html>
  );
}
